---
- hosts: localhost
  vars:
    vcenter_hostname: 192.168.1.182
    vcenter_user: administrator@linuxzera.local
    vcenter_pass: '#Alvivic200811#'
    esxhost: 192.168.1.180
    name: "{{ vm_name }}"
    notes: Ansible Test
    dumpfacts: False

  tasks:
  - name: Gather all VMs information
    vmware_vm_info:
      hostname: '192.168.1.182'
      username: 'administrator@linuxzera.local'
      password: '#Alvivic200811#'
      validate_certs: no
    register: all_vm_info
    delegate_to: localhost


  - name: Gather a list of all powered on VMs
    set_fact:
      on_vm: "{{ all_vm_info.virtual_machines | json_query(query) }}"
    vars:
      query: "[?power_state=='poweredOn']"
    register: jsoncontent

  - name: Gather a list of all powered on VM names
    debug: msg="{{ on_vm | json_query(jmesquery) }}"
    vars:
      jmesquery: "[*].{guest_name: guest_name, ip_address: ip_address}"

